name: dublin-electricity-network

channels:
  - conda-forge
  - defaults

dependencies:
  - dask
  - geopandas
  - momepy
  - openpyxl
  - osmnx
  - pygeos
  - seaborn
  - sklearn 
  - sparse_dot_topn
  
  - black
  - ipykernel
  - ipywidgets
  - jupytext
  - poetry
  - pre-commit

  - pip:
    - string_grouper
