name: dublin-electricity-network

channels:
  - conda-forge
  - defaults

dependencies:
  - dask
  - geopandas
  - matplotlib
  - momepy
  - openpyxl
  - pygeos
  - scikit-learn
  
  - black
  - ipykernel
  - ipywidgets
  - jupytext
  - poetry
  - pre-commit
