name: des

channels:
  - conda-forge
  - defaults

dependencies:
  - geopandas
  - pandas
  - momepy
  - scikit-learn
  - tqdm
  - descartes
  - matplotlib
  - geopy
  
  - notebook
  - jupytext
  - poetry
  - black
  
  - pip
  - pip:
    - git+https://github.com/codema-dev/dublin-electricity-substations

