name: dublin-electricity-network

channels:
  - conda-forge
  - defaults

dependencies:
  - dask
  - geopandas
  - momepy
  - openpyxl
  - osmnx
  - pygeos
  - sklearn
  
  - black
  - ipykernel
  - ipywidgets
  - jupytext
  - poetry
  - pre-commit
