name: esb

channels:
  - conda-forge
  - defaults

dependencies:
  - dask
  - descartes
  - geopandas
  - momepy
  - numpy
  - networkx
  - pandas
  - pygeos
  - scikit-learn
  - scipy
  - shapely
  - tqdm
  - matplotlib
  
  - notebook
  - jupytext
  - ipywidgets
  - poetry
  - black
  - pre-commit
  
  - pip
  - pip:
    - git+https://github.com/codema-dev/esb-network-pylib

